### ISSUE TITLE
For a simple rsyslog configuration basic input to 9 file outputs, role repeats same tasks over and over ( 433 tasks )

### ISSUE THREAD

**Issue by yanpain** [linux-system-roles/logging#188]
PLAY RECAP  *** hostname : ok=221  changed=3    unreachable=0    failed=0    skipped=209  rescued=0    ignored=0

variables :
```
logging_inputs:
  - name: system
    type: basics
logging_outputs:
  - name: localfs
    type: files
    state: absent
  - name: fw_arcsight
    type: forwards
    severity: info
    target: 1.1.1.1
    udp_port: 514
  - name: console
    type: files
    facility: kernel
    path: /dev/console
  - name: secure
    type: files
    facility: authpriv
    path: /var/log/secure
  - name: messages_exclude_oracle_audit
    type: files
    severity: info
    exclude:
      - authpriv.none
      - cron.none
      - mail.none
      - local1.none
    path: /var/log/messages
  - name: mail
    type: files
    facility: mail
    path: -/var/log/maillog
  - name: cron
    type: files
    facility: cron
    path: -/var/log/cron
  - name: emergency
    type: files
    severity: emerg
    path: :omusrmsg:*
  - name: boot
    type: files
    facility: local7
    path: /var/log/boot.log
  - name: oracle_audit
    type: files
    facility: local1
    severity: warning
    path: /arcsight/audit.log
```

**Comment by richm** [comment]
@yanpain are you saying that the role is not idempotent given these inputs?

**Comment by yanpain** [comment]
Indempotence is respected, my concern is that it will run each tasks too many times for nothing

**Comment by richm** [comment]
> Indempotence is respected, my concern is that it will run each tasks too many times for nothing

Ah, so your concern is that the tasks need to be optimized somehow?  e.g. combine multiple tasks into one, get rid of or skip unnecessary tasks, etc.?
What about the running time?

**Comment by nhosoi** [comment]
@yanpain, I ran your configuration, which successfully finished with 701 TASKs. Since each task size is pretty small and there are 9 outputs, the total count of tasks may look many, but IMHO it's normal.

Also, I'm interested in your "variables". Are the variables in your report complete ones or a subset of them? I don't see logging_flows to represent the relationship between the inputs and the outputs.

I added this logging_flows to your variables
```
        logging_flows:
          - name: flow
            inputs: [system]
            outputs:
              - fw_arcsight
              - console
              - secure
              - messages_exclude_oracle_audit
              - mail
              - cron
              - emergency
              - boot
              - oracle_audit
```
It generates the input file 90-input-basics-system.conf as follows. To pass the logs read from imjournal to the outputs, the calls are needed. 
```
# Ansible managed
module(load="imuxsock"    # provides support for local system logging (e.g. via logger command)
       SysSock.Use="off") # Turn off message reception via local log socket.
module(load="imjournal"
       StateFile="/var/lib/rsyslog/imjournal.state"
       RateLimit.Burst="20000"
       RateLimit.Interval="600"
       PersistStateInterval="10")
if
  ($inputname == "imjournal" or $inputname == "imuxsock")
  then {
    call console
}
if
  ($inputname == "imjournal" or $inputname == "imuxsock")
  then {
    call secure
}
if
  ($inputname == "imjournal" or $inputname == "imuxsock")
  then {
    call messages_exclude_oracle_audit
}
if
  ($inputname == "imjournal" or $inputname == "imuxsock")
  then {
    call mail
}
if
  ($inputname == "imjournal" or $inputname == "imuxsock")
  then {
    call cron
}
if
  ($inputname == "imjournal" or $inputname == "imuxsock")
  then {
    call emergency
}
if
  ($inputname == "imjournal" or $inputname == "imuxsock")
  then {
    call boot
}
if
  ($inputname == "imjournal" or $inputname == "imuxsock")
  then {
    call oracle_audit
}
if
  ($inputname == "imjournal" or $inputname == "imuxsock")
  then {
    call fw_arcsight
}
```
There is one more small issue.  `kernel` is not a valid facility keyword.  Please replace it with `kern`. https://www.rsyslog.com/doc/v8-stable/configuration/filters.html
```
  - name: console
    type: files
    facility: kernel <== kern
    path: /dev/console
```

**Comment by yanpain** [comment]
I was drawned to use this module because its supported by RedHat now, like others linux-system-roles I now use to provision my RHEL environment. My syslog configuration needs are on a Linux server hosting business applications scope, I'm not building a big syslog receiving server so according to my current experience, this module is a lot of overhead to configure my simple rsyslogd on all my environment, I think it was not meant to do that. A concern is it doesn't seem to be optimized to finish quickly also, redundantly running the same tasks over and over with no apparent reason in my context. I guess I will just write a simple role with templates for the rsyslogd config, unless you have a way to get it to run in a more optimized way.
I added the flow as instructed in the previous post, no luck, launched it and it is still running repeating the same tasks endlessly, for about 30 minutes now
but please correct me if I misunderstood something, thanks for your work !

ansible.log ( first and last timestamps ) run took 19 minutes
```
2020-12-03 15:07:10,466 p=155883 u=yan n=ansible | TASK [/usr/share/ansible/roles/logging/roles/rsyslog : Set platform/version specific variables] *****************************************************************************
<...>
2020-12-03 15:26:49,932 p=156093 u=yan n=ansible | RUNNING HANDLER [/usr/share/ansible/roles/logging/roles/rsyslog : restart rsyslogd] *****************************************************************************************
```

number of tasks run/skipped :
```
PLAY RECAP ***********************************************************************************************************************************
scbelepldora71.ld.labecc.cibc.com : ok=223  changed=3    unreachable=0    failed=0    skipped=209  rescued=0    ignored=0
```

```
variables config used : 
logging_inputs:
  - name: system
    type: basics
logging_outputs:
  - name: localfs
    type: files
    state: absent
  - name: fw_arcsight
    type: forwards
    severity: info
    target: 1.1.1.1
    udp_port: 514
  - name: console
    type: files
    facility: kern
    path: /dev/console
  - name: secure
    type: files
    facility: authpriv
    path: /var/log/secure
  - name: messages_exclude_oracle_audit
    type: files
    severity: info
    exclude:
      - authpriv.none
      - cron.none
      - mail.none
      - local1.none
    path: /var/log/messages
  - name: mail
    type: files
    facility: mail
    path: -/var/log/maillog
  - name: cron
    type: files
    facility: cron
    path: -/var/log/cron
  - name: emergency
    type: files
    severity: emerg
    path: :omusrmsg:*
  - name: boot
    type: files
    facility: local7
    path: /var/log/boot.log
  - name: oracle_audit
    type: files
    facility: local1
    severity: warning
    path: /arcsight/audit.log
logging_flows:
  - name: flow
    inputs: [system]
    outputs:
      - console
      - secure
      - messages_exclude_oracle_audit
      - mail
      - cron
      - emergency
      - boot
      - oracle_audit
      - fw_arcsight
```
