### ISSUE TITLE
RELP: the port definition for client side is not honored

### ISSUE THREAD

**Issue by sopos** [linux-system-roles/logging#203]
No matter what, the resulting port for RELP is 20514
```
    logging_outputs:
      - name: relp_output
        type: relp
        server_host: 10.0.138.114
        port: 6514
        tls: true
        ca_cert_src: /tmp/tmp.YOFEgWl40t/ca.pem
        cert_src: /tmp/tmp.YOFEgWl40t/client-cert.pem
        private_key_src: /tmp/tmp.YOFEgWl40t/client-key.pem
        permitted_servers:
          - hostX
```
