### ISSUE TITLE
RELP: wrong reference to the input on server side

### ISSUE THREAD

**Issue by sopos** [linux-system-roles/logging#204]
the following flow will create bad condition in the resulting config
```
   logging_flows:
      - name: flows
        inputs: [system_input, remote_input]
        outputs: [files_output]
```

```
if ($inputname == "remote_input_1" ) ..
```

the suffix `_1` should not be there.
